openapi: 3.0.0
info:
  title: Pokemon API
  description: API providing information about Pokemon!
  version: "1.0"
servers:
- url: /
paths:
  /pokemon:
    get:
      summary: Gets information about one or more Pokemon.
      operationId: pokemon_get
      parameters:
      - name: name
        in: query
        description: Name of the Pokemon to get.
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: exact
        in: query
        description: "Whether to match the name exactly, or to search as a substring\
          \ on the Pokemon names."
        required: false
        style: form
        explode: true
        schema:
          type: boolean
          default: true
      - name: poke_type
        in: query
        description: Filter by Pokemon type.
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: A JSON array of Pokemons.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                x-content-type: application/json
        default:
          description: Invalid request!
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /pokemon/all:
    get:
      summary: Gets information about all Pokemon.
      operationId: pokemon_all_get
      responses:
        "200":
          description: A JSON array of Pokemons.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                x-content-type: application/json
        default:
          description: Invalid request!
      x-openapi-router-controller: swagger_server.controllers.default_controller
  /moves:
    get:
      summary: Gets information about one or more Pokemon attack moves!
      operationId: moves_get
      parameters:
      - name: name
        in: query
        description: "Name of the move to get. If ommited, at least one of the\
          \ other filters must be present."
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: power
        in: query
        description: "Minimum power of the move. If ommited, at least one of the other\
          \ filters must be present."
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: accuracy
        in: query
        description: "Minimum accuracy of the move. If ommited, at least one of the\
          \ other filters must be present."
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        "200":
          description: A JSON of one or more Pokemon attack moves.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                x-content-type: application/json
        "400":
          description: Bad request. At least one of the parameters must be defined.
        default:
          description: Invalid request!
      x-openapi-router-controller: swagger_server.controllers.default_controller
components: {}

