# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse400(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, message: str=None, wrong_parameter: str=None):  # noqa: E501
        """InlineResponse400 - a model defined in Swagger

        :param message: The message of this InlineResponse400.  # noqa: E501
        :type message: str
        :param wrong_parameter: The wrong_parameter of this InlineResponse400.  # noqa: E501
        :type wrong_parameter: str
        """
        self.swagger_types = {
            'message': str,
            'wrong_parameter': str
        }

        self.attribute_map = {
            'message': 'message',
            'wrong_parameter': 'wrong_parameter'
        }
        self._message = message
        self._wrong_parameter = wrong_parameter

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse400':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_400 of this InlineResponse400.  # noqa: E501
        :rtype: InlineResponse400
        """
        return util.deserialize_model(dikt, cls)

    @property
    def message(self) -> str:
        """Gets the message of this InlineResponse400.

        The error message.  # noqa: E501

        :return: The message of this InlineResponse400.
        :rtype: str
        """
        return self._message

    @message.setter
    def message(self, message: str):
        """Sets the message of this InlineResponse400.

        The error message.  # noqa: E501

        :param message: The message of this InlineResponse400.
        :type message: str
        """

        self._message = message

    @property
    def wrong_parameter(self) -> str:
        """Gets the wrong_parameter of this InlineResponse400.

        The name of the parameter causing the error.  # noqa: E501

        :return: The wrong_parameter of this InlineResponse400.
        :rtype: str
        """
        return self._wrong_parameter

    @wrong_parameter.setter
    def wrong_parameter(self, wrong_parameter: str):
        """Sets the wrong_parameter of this InlineResponse400.

        The name of the parameter causing the error.  # noqa: E501

        :param wrong_parameter: The wrong_parameter of this InlineResponse400.
        :type wrong_parameter: str
        """

        self._wrong_parameter = wrong_parameter
