# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, id: int=None, first_name: str=None, last_name: str=None, email: str=None, gender: str=None, ip_address: str=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param id: The id of this InlineResponse200.  # noqa: E501
        :type id: int
        :param first_name: The first_name of this InlineResponse200.  # noqa: E501
        :type first_name: str
        :param last_name: The last_name of this InlineResponse200.  # noqa: E501
        :type last_name: str
        :param email: The email of this InlineResponse200.  # noqa: E501
        :type email: str
        :param gender: The gender of this InlineResponse200.  # noqa: E501
        :type gender: str
        :param ip_address: The ip_address of this InlineResponse200.  # noqa: E501
        :type ip_address: str
        """
        self.swagger_types = {
            'id': int,
            'first_name': str,
            'last_name': str,
            'email': str,
            'gender': str,
            'ip_address': str
        }

        self.attribute_map = {
            'id': 'id',
            'first_name': 'first_name',
            'last_name': 'last_name',
            'email': 'email',
            'gender': 'gender',
            'ip_address': 'ip_address'
        }
        self._id = id
        self._first_name = first_name
        self._last_name = last_name
        self._email = email
        self._gender = gender
        self._ip_address = ip_address

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this InlineResponse200.

        The user ID.  # noqa: E501

        :return: The id of this InlineResponse200.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this InlineResponse200.

        The user ID.  # noqa: E501

        :param id: The id of this InlineResponse200.
        :type id: int
        """

        self._id = id

    @property
    def first_name(self) -> str:
        """Gets the first_name of this InlineResponse200.

        The user's first name.  # noqa: E501

        :return: The first_name of this InlineResponse200.
        :rtype: str
        """
        return self._first_name

    @first_name.setter
    def first_name(self, first_name: str):
        """Sets the first_name of this InlineResponse200.

        The user's first name.  # noqa: E501

        :param first_name: The first_name of this InlineResponse200.
        :type first_name: str
        """

        self._first_name = first_name

    @property
    def last_name(self) -> str:
        """Gets the last_name of this InlineResponse200.

        The user name.  # noqa: E501

        :return: The last_name of this InlineResponse200.
        :rtype: str
        """
        return self._last_name

    @last_name.setter
    def last_name(self, last_name: str):
        """Sets the last_name of this InlineResponse200.

        The user name.  # noqa: E501

        :param last_name: The last_name of this InlineResponse200.
        :type last_name: str
        """

        self._last_name = last_name

    @property
    def email(self) -> str:
        """Gets the email of this InlineResponse200.

        The user's email.  # noqa: E501

        :return: The email of this InlineResponse200.
        :rtype: str
        """
        return self._email

    @email.setter
    def email(self, email: str):
        """Sets the email of this InlineResponse200.

        The user's email.  # noqa: E501

        :param email: The email of this InlineResponse200.
        :type email: str
        """

        self._email = email

    @property
    def gender(self) -> str:
        """Gets the gender of this InlineResponse200.

        The user's gender.  # noqa: E501

        :return: The gender of this InlineResponse200.
        :rtype: str
        """
        return self._gender

    @gender.setter
    def gender(self, gender: str):
        """Sets the gender of this InlineResponse200.

        The user's gender.  # noqa: E501

        :param gender: The gender of this InlineResponse200.
        :type gender: str
        """

        self._gender = gender

    @property
    def ip_address(self) -> str:
        """Gets the ip_address of this InlineResponse200.

        The user's ip address.  # noqa: E501

        :return: The ip_address of this InlineResponse200.
        :rtype: str
        """
        return self._ip_address

    @ip_address.setter
    def ip_address(self, ip_address: str):
        """Sets the ip_address of this InlineResponse200.

        The user's ip address.  # noqa: E501

        :param ip_address: The ip_address of this InlineResponse200.
        :type ip_address: str
        """

        self._ip_address = ip_address
